[package]
name = "test-caller-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.test-caller]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.47.5"
