[package]
name = "helper-contract-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.helper-contract]
path = ".."

[dependencies.multiversx-sc-meta-lib]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "3050fab"
default-features = false
