// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            3
// Async Callback (empty):               1
// Total number of exported functions:   6

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    helper_contract
    (
        init => init
        upgrade => upgrade
        setBridgeProxyAddress => set_bridge_proxy_address
        callDeposit => call_deposit
        getBridgeProxyAddress => bridge_proxy_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
