// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            3
// Async Callback (empty):               1
// Total number of exported functions:   6

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mock_esdt_safe
    (
        init => init
        upgrade => upgrade
        createRefundTransaction => create_refund_transaction
        withdrawTransactionFees => withdraw_transaction_fees
        withdrawRefundFeesForEthereum => withdraw_refund_fees_for_ethereum
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
