// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           12
// Async Callback (empty):               1
// Promise callbacks:                    1
// Total number of exported functions:  15

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    bridge_proxy
    (
        init => init
        upgrade => upgrade
        deposit => deposit
        executeWithAsnyc => execute_with_async
        getPendingTransactionById => get_pending_transaction_by_id
        setupMultiTransfer => set_multi_transfer_contract_address
        setupEsdtSafe => set_esdt_safe_contract_address
        getMultiTransferAddress => multi_transfer_address
        getEsdtSafeAddress => esdt_safe_address
        getPendingTransactions => pending_transactions
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        execution_callback => execution_callback
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
