// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback:                       1
// Total number of exported functions:  10

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    bridge_proxy
    (
        init => init
        deposit => deposit
        executeWithAsnyc => execute_with_async
        refundTransactions => refund_transactions
        setupMultiTransfer => set_multi_transfer_contract_address
        getEthTransactionById => get_eth_transaction_by_id
        getMultiTransferAddress => multi_transfer_address
        getEthTransactionList => eth_transaction_list
        getEthFailedTransactionList => eth_failed_transaction_list
    )
}

multiversx_sc_wasm_adapter::async_callback! { bridge_proxy }
