[settings]
main = "main"

[contracts.main]
name = "esdt-safe"

[contracts.set_mint_balances]
name = "esdt-safe-test"
external-view = true
add-unlabelled = false
add-labels = ["test-only"]

[[proxy]]
path = "../bridge-proxy/src/esdt_safe_proxy.rs"