[settings]

[[proxy]]
path = "../bridged-tokens-wrapper/src/esdt_safe_proxy.rs"

[[proxy]]
path = "../multi-transfer-esdt/src/esdt_safe_proxy.rs"

[[proxy]]
path = "../multisig/src/esdt_safe_proxy.rs"

[[proxy]]
path = "src/esdt_safe_proxy.rs"