[settings]

[[proxy]]
path = "../multisig/src/esdt_safe_proxy.rs"
add-unlabelled = false
add-endpoints = [
    "init",
    "upgrade",
    "unpause",
    "setMultiTransferContractAddress",
    "addTokenToWhitelist",
    "distributeFees",
    "getCurrentTxBatch",
    "initSupply",
    "setTransactionBatchStatus",
    "getBatch",
    "pause",
    "setFeeEstimatorContractAddress",
    "setEthTxGasLimit",
    "setDefaultPricePerGasUnit",
    "setTokenTicker",
    "addTokenToWhitelist",
    "setMultiTransferContractAddress",
    "removeTokenFromWhitelist",
    "setMaxTxBatchSize",
    "setMaxTxBatchBlockDuration",
    "setMaxBridgedAmount",
]

[[proxy]]
path = "../bridged-tokens-wrapper/src/esdt_safe_proxy.rs"
add-unlabelled = false
add-endpoints = [
    "createTransaction"
]

[[proxy]]
path = "../multi-transfer-esdt/src/esdt_safe_proxy.rs"
add-unlabelled = false
add-endpoints = [
    "upgrade",
    "unpause",
    "setMultiTransferContractAddress",
    "addTokenToWhitelist",
    "getTokens",
    "addRefundBatch"
]