// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    test_caller
    (
        init => init
        upgrade => upgrade
        callPayable => call_payable
        callNonPayable => call_non_payable
        callPayableWithParams => call_payable_with_params
        callPayableWithBuff => call_payable_with_buff
        getCalledDataParams => get_called_data_params
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
