[package]
name = "mock-bridge-proxy-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.mock-bridge-proxy]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.55.0"
default-features = false
