[package]
name = "mock-bridge-proxy-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.mock-bridge-proxy]
path = ".."

[dependencies.multiversx-sc-meta-lib]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "3050fab"
default-features = false
