[package]
name = "bridge-proxy"
version = "0.0.0"
authors = ["Costin Carabaș <costin.carabas@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "src/bridge-proxy.rs"

[dependencies.transaction]
path = "../common/transaction"

[dependencies.eth-address]
path = "../common/eth-address"

[dependencies.esdt-safe]
path = "../esdt-safe"

[dependencies.multiversx-sc]
version = "=0.47.5"

[dependencies.multiversx-sc-modules]
version = "0.47.5"

[dependencies.adder]
git = "https://github.com/multiversx/mx-contracts-rs"
rev = "a2d5eac"

[dev-dependencies]
num-bigint = "0.4.2"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.47.5"
