[package]
name = "mock-proxies"
version = "0.0.0"
authors = ["MultiversX <contact@multiversx.com>"]
edition = "2018"

[dependencies.multiversx-sc]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "3050fab"
