[package]
name = "mock-price-aggregator-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.mock-price-aggregator]
path = ".."

[dependencies.multiversx-sc-meta-lib]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "215503a"

default-features = false
