[settings]

[[proxy]]
path = "src/multisig_proxy.rs"
add-unlabelled = false
add-endpoints = [
    "init",
    "upgrade",
    "stake",
    "proposeEsdtSafeSetCurrentTransactionBatchStatus",
    "unpause",
    "getAllStakedRelayers",
    "proposeMultiTransferEsdtBatch",
    "sign",
    "performAction",
    "wasTransferActionProposed",
    "getActionIdForTransferBatch",
    "getCurrentRefundBatch",
    "moveRefundBatchToSafeFromChildContract",
]
