// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           61
// Async Callback (empty):               1
// Total number of exported functions:  63

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    multisig
    (
        distributeFeesFromChildContracts
        stake
        unstake
        proposeEsdtSafeSetCurrentTransactionBatchStatus
        proposeMultiTransferEsdtBatch
        moveRefundBatchToSafe
        performAction
        sign
        upgradeChildContractFromSource
        addBoardMember
        removeUser
        slashBoardMember
        changeQuorum
        addMapping
        clearMapping
        pauseEsdtSafe
        unpauseEsdtSafe
        changeFeeEstimatorContractAddress
        changeElrondToEthGasLimit
        changeDefaultPricePerGasUnit
        changeTokenTicker
        esdtSafeAddTokenToWhitelist
        esdtSafeRemoveTokenFromWhitelist
        esdtSafeSetMaxTxBatchSize
        esdtSafeSetMaxTxBatchBlockDuration
        esdtSafeSetMaxBridgedAmountForToken
        multiTransferEsdtSetMaxBridgedAmountForToken
        multiTransferEsdtSetMaxRefundTxBatchSize
        multiTransferEsdtSetMaxRefundTxBatchBlockDuration
        multiTransferEsdtSetWrappingContractAddress
        getQuorum
        getNumBoardMembers
        getRequiredStakeAmount
        getAmountStaked
        getSlashAmount
        getSlashedTokensAmount
        getLastExecutedEthBatchId
        getLastExecutedEthTxId
        getErc20AddressForTokenId
        getTokenIdForErc20Address
        getEsdtSafeAddress
        getMultiTransferEsdtAddress
        getCurrentTxBatch
        getCurrentRefundBatch
        wasActionExecuted
        wasTransferActionProposed
        getActionIdForTransferBatch
        wasSetCurrentTransactionBatchStatusActionProposed
        getActionIdForSetCurrentTransactionBatchStatus
        signed
        userRole
        getAllBoardMembers
        getAllStakedRelayers
        getActionSignerCount
        getActionValidSignerCount
        quorumReached
        getActionLastIndex
        getActionData
        pause
        unpause
        isPaused
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
