// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            1
// Async Callback (empty):               1
// Total number of exported functions:   4

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mock_multi_transfer_esdt
    (
        init => init
        upgrade => upgrade
        addUnprocessedRefundTxToBatch => add_unprocessed_refund_tx_to_batch
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
