[package]
name = "fee-estimator-module"
version = "0.0.0"
authors = ["dorin-iancu <dorin.iancu@elrond.com>"]
edition = "2018"

[dependencies.multiversx-sc]
version = "0.56.1"

[dependencies.storage-module]
path = "../storage-module"

[dev-dependencies.multiversx-sc-scenario]
version = "0.56.1"
