[package]
name = "fee-estimator-module"
version = "0.0.0"
authors = [ "dorin-iancu <dorin.iancu@elrond.com>",]
edition = "2018"

[dependencies.elrond-wasm]
version = "0.22.10"

[dev-dependencies.elrond-wasm-debug]
version = "0.22.10"
