[settings]

[[proxy]]
path = "../multisig/src/multi_transfer_esdt_proxy.rs"
add-unlabelled = false
add-endpoints = [
    "init",
    "moveRefundBatchToSafe",
    "batchTransferEsdtToken",
    "getFirstBatchAnyStatus",
    "setEsdtSafeContractAddress",
    "setMaxBridgedAmount",
    "setMaxTxBatchSize",
    "setMaxTxBatchBlockDuration",
    "setWrappingContractAddress"
]

[[proxy]]
path = "/src/multi_transfer_esdt_proxy.rs"
add-unlabelled = false
add-endpoints = [
    "init",
    "moveRefundBatchToSafe",
    "batchTransferEsdtToken",
    "getFirstBatchAnyStatus",
    "setEsdtSafeContractAddress",
    "setWrappingContractAddress",
    "setBridgeProxyContractAddress",
]
