[package]
name = "mock-esdt-safe-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.mock-esdt-safe]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.53.2"
default-features = false
