[package]
name = "bridge-proxy-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.bridge-proxy]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.47.4"
