[package]
name = "bridge-proxy-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.bridge-proxy]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "=0.55.0"
