name: On pull request, build contracts

on:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@v3.2.0
    with:
      image_tag: v6.1.0
      package_whole_project_src: true
