name: On pull request, build contracts

on:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v2.3.4
    with:
      image_tag: v4.2.1
      package_whole_project_src: true
      skip_preliminary_checks: true