[package]
name = "egld-esdt-swap-abi"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.egld-esdt-swap]
path = ".."

[dependencies.elrond-wasm]
version = "0.18.2"

[dependencies.elrond-wasm-debug]
version = "0.18.2"
